### ISSUE TITLE
when trying to apply for nc file directly ...i have this issue?

### ISSUE THREAD

**Issue by Shivagopalshrestha** [Yuanchao-Xu/hyfo#1]
biasFactor <-  getBiasFactor(nc, nc1)
Error in if (!is.na(memberIndex)) { : argument is of length zero

**Comment by Yuanchao-Xu** [comment]
@Shivagopalshrestha could I have your a sample for your nc and nc1 data for me to check?

**Comment by Shivagopalshrestha** [comment]
Yes .
I am attaching the files here..

My observed data is prism.
loadncdf failed to load orignal_obsPRISM so
i extracted the data and date and pasted into cmip_his and created obs_PRISM.

LoadNCDF was successful but biasfactor failed!!
[cmip_his.zip](https://github.com/Yuanchao-Xu/hyfo/files/2420059/cmip_his.zip)
[obs_PRISM.zip](https://github.com/Yuanchao-Xu/hyfo/files/2420061/obs_PRISM.zip)
[orignal_obsPRSIM.zip](https://github.com/Yuanchao-Xu/hyfo/files/2420069/orignal_obsPRSIM.zip)

**Comment by Yuanchao-Xu** [comment]
Hi @Shivagopalshrestha 

Now the issue's been solved, and I'll submit the changes to cran. If you want to use it now, you can use the latest version in github by `devtools::install_github('Yuanchao-Xu/hyfo')`

By the way, the ncdf file in your orignal_obsPRSIM.zip doesn't work, due to its non-standard time unit. The other two work well. 

If you do need to use the ncdf file in orignal_obsPRSIM.zip, you can folk hyfo, and open ncdf.R in your Rstudio, change line 114 from `timeUnit <- strsplit(var$dim[[dimIndex[3]]]$units, split = ' since')[[1]][1]` to `timeUnit <- "days"`. But keep in mind, this change will only apply to your case this time.

**Comment by Shivagopalshrestha** [comment]
Thank you so much for the prompt response. It worked.
Hi @Yuanchao-Xu 

Thank you for the prompt response.
I am checking for the results are good. I will let you know if any other issue.
I  am trying to find how the bias correction is being performed for eqm and how larger value in futuredata.

frc_new <- biasCorrect(frc, hindcast, obs, method = 'eqm', scaleType = 'constant',preci = TRUE)

I was searching for the literature and explaination for these 2 constraints
  **scaleType = 'constant',preci = TRUE**
Thank you

**Comment by Yuanchao-Xu** [comment]
@Shivagopalshrestha 
about the two arguments, you can just check the help document attached to the function

**Comment by Shivagopalshrestha** [comment]
Can i please get your conference paper on this?
I am tyring to find how the function works?

 1. Is eqm performing on monthly basis or done whole the timeseries as one?
  2. how is extrapolation carried out for new sets of data?
 3. Does is check the properties like annnual rain amount and no of rainy days? 

Thank you

**Comment by Yuanchao-Xu** [comment]
@Shivagopalshrestha 

Sorry I don't have the paper myself and I've left DHI. But I have the title of the related presentation in CMWR 2016 "Seasonal Forecasting for Water Resource Management: Reservoir inflows
and uncertainties", through which you may find something on the internet.

And for your question about the biascorrect function, they are explained in the documentation. you can type in `?biasCorrect` or check [here](https://github.com/Yuanchao-Xu/hyfo/blob/master/R/biasCorrect(generic).R)
