### ISSUE TITLE
BIAS CORRECTION FOR MULTIPLE TIME SERIES

### ISSUE THREAD

**Issue by Lucia2** [Yuanchao-Xu/hyfo#3]
I have one dataset with 33 stations for observed station data and hindcast for the same stations, so I need to get the bias factor for each station and apply it to correct the projection for each station.I have been following the guideline but when i input my dataset,i get an error;" Error in getClass(Class, where = topenv(parent.frame())) : 
  “biasFactor.multiMember” is not a defined class".

**Comment by Yuanchao-Xu** [comment]
@Lucia2 the error may be because you made multiple time series as input at the same time. Bias correction can only be conducted between two time series. Therefore, if you have 33 pairs of obs data and hindcast data, you have to bias correct for each station.

However, since bias correction is mainly to deal with a model, if all of your hindcast data is obtained by the same forecasting model, technically you can just bias correct one station and apply the bias factor to all the rest to have a rough result. 

However, the safest way to do with your data is still bias correct every station, which can be done by simple loops.
