### ISSUE TITLE
Error in loadNcdf(filePath, "T2") : Your file has less than 3 dimensions.

### ISSUE THREAD

**Issue by lodhajyoti** [Yuanchao-Xu/hyfo#7]
[T2_raj_2013-01-04.zip](https://github.com/Yuanchao-Xu/hyfo/files/3622170/T2_raj_2013-01-04.zip)
Hi
 When I am running the following command I am again getting the same error, irrespective of I changed the varname=Tas i,e name of the variable.

 filePath <- system.file("extdata", "Tas_raj_2013-01-04.nc", package = "hyfo")
varname <- getNcdfVar(filePath)    
histrocial <- loadNcdf(filePath, "Tas")
Error in loadNcdf(filePath, "Tas") : Your file has less than 3 dimensions.

Please help me solve this problem. I am attaching my sample file below.
[Tas_raj_2013-01-04.zip](https://github.com/Yuanchao-Xu/hyfo/files/3622141/Tas_raj_2013-01-04.zip)

**Comment by Yuanchao-Xu** [comment]
Hi @lodhajyoti 

That's because your ncdf file has different dimension names from others: they are x and y, instead of lon and lat. 

It's been fixed in the latest `hyfo 1.4.1`. 

I have already submitted it to CRAN, but it may take some time to be updated. Before that, you can use `devtools::install_github('Yuanchao-Xu/hyfo')` to download directly from github.

**Comment by lodhajyoti** [comment]
Thanks a Lot for solving my issues. Meanwhile I also  converted my data to lon lat format using cdo operators and successfully run your package.
Thanks.

**Comment by Yuanchao-Xu** [comment]
Welcome~
